service: bundesliga
frameworkVersion: '3'
disabledDeprecations: '*'

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-warmup
  - serverless-offline
  - serverless-plugin-optimize
  
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  region: 'eu-central-1'
  memorySize: 1024
  timeout: 30

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    TITLE: ${env):TITLE}
    AUTHOR: ${env):AUTHOR}
    DB_HOST: ${env):DB_HOST}
    DB_PORT: ${env):DB_PORT}
    DB_USERNAME: ${env):DB_USERNAME}
    DB_PASSWORD: ${env):DB_PASSWORD}
    DB_DATABASE: ${env):DB_DATABASE}
    JWT_SECRET: ${env):JWT_SECRET}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
  kickOff:
    handler: dist/match.warmup
    events:
      - http:
          method: ANY
          path: /warmup
package:
  individually: true
